<a href="https://colab.research.google.com/github/PJdin/PJdin/blob/main/AIDL_20220304.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [20220304.md](https://github.com/MyDearGreatTeacher/2022_1_courses/blob/main/%E4%BA%BA%E5%B7%A5%E6%99%BA%E6%85%A7%E8%88%87%E6%B7%B1%E5%BA%A6%E5%AD%B8%E7%BF%92/%E4%B8%8A%E8%AA%B2%E7%AD%86%E8%A8%98/20220304.md)

確認開發環境的套件版本

In [ ]:
pip list

Package                       Version
----------------------------- ---------------------
absl-py                       1.0.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.2.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.11.4
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.4.0
audioread                     2.1.9
autograd                      1.3
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        4.1.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.4
branca                        0.4.2
bs4                           0.0.1
CacheC

載入套件及輸出版本

In [ ]:
# panel data的延伸 可以用來執行強大的資料分析
import pandas as pd
print("pandas version:%s"% pd.__version__)
# python的視覺化套件 其中包含兩個重要模組 pylab pyplot 可以利用matpolib創建各種圖形(折線圖、直方圖、散佈圖等)
import matplotlib
print("matplotlib version:%s"% matplotlib.__version__)
# python的擴充模組程式庫 資源高階大量的維度陣列與矩陣運算 也針對陣列運算圖供大量的數學函式庫
import numpy as np
print("numpy version:%s"% np.__version__)
# 基於python的機器學習工具包
import sklearn
print("scikit-learn version:%s"% sklearn.__version__)

pandas version:1.3.5
matplotlib version:3.2.2
numpy version:1.21.5
scikit-learn version:1.0.2


如何學習或是使用套件

In [ ]:
import numpy as np
b = np.linspace(0, 2, 4)
b
# array([0.        , 0.66666667, 1.33333333, 2.        ])

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [ ]:
c = np.linspace(0, 2, 4, endpoint=False) 
c
# array([0. , 0.5, 1. , 1.5])

array([0. , 0.5, 1. , 1.5])

# [numpy 學習主題 20220304b.md](https://github.com/MyDearGreatTeacher/2022_1_courses/blob/main/%E4%BA%BA%E5%B7%A5%E6%99%BA%E6%85%A7%E8%88%87%E6%B7%B1%E5%BA%A6%E5%AD%B8%E7%BF%92/%E4%B8%8A%E8%AA%B2%E7%AD%86%E8%A8%98/20220304b.md)

adarray的屬性:維度(dimension):ndim

In [ ]:
ar2=np.array([[0,3,5],[2,8,7]]) #2D array
ar2.ndim

2
(2, 3)


ndarry的屬性:形狀(shape):shape

In [ ]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]]) #產生一個2D array
ar2.shape

(2, 3)

ndarray的屬性:大小(屬性個數):size

In [ ]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]]) #產生一個2D array
ar2.size

6

ndarray的屬性:dtype(資料型態:data type)

In [ ]:
import numpy as np

ar1=np.array([2,4,6,8]); 
ar1.dtype

dtype('int64')

In [ ]:
ar2=np.array([2,-1,6,3], dtype='float'); 
ar2
ar2.dtype

dtype('float64')

In [ ]:
import numpy as np

ar3=np.array([2.,4,6,8]); 

ar3.dtype

dtype('float64')

ndarray的運算:型態轉換|astype()函式

In [ ]:
f_ar = np.array([13,-3,8.88])
f_ar

array([13.  , -3.  ,  8.88])

In [ ]:
intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

建立ndarray

In [ ]:
使用numpy.linspace產生陣列

In [ ]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(2.0,3.0,num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

create identity matrix(對角線的地方為1其餘為0)

In [ ]:
ar9=np.eye(3);
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

create diagonal array (對角)

In [ ]:
ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [ ]:
import numpy as np
b=np.array([range(i,i+3)for i in [2,4,6]])
b



array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
b.shape

(3, 3)

In [ ]:
b.ndim

2

In [ ]:
b.dtype

dtype('int64')

np.tile(陣列,重複幾次)

In [ ]:
a=np.array([0,1,2])
np.tile(a,2)

array([0, 1, 2, 0, 1, 2])

In [ ]:
np.tile(a,(2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

np.tile(a,(2,2))

Reduction Operations

Universal Functions

In [ ]:
ar=range(1000)
%timeit [ar[i]**3 for i in ar]

1000 loops, best of 5: 408 µs per loop


In [ ]:
ar=np.arange(1000)
%timeit ar**3

The slowest run took 24.74 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 3.65 µs per loop
